version: '3.8'
networks:
  akuntansi_dev:

services:
  akuntansi_db_dev:
    image: mysql:8.0
    container_name: akuntansi_db_dev
    restart: always
    environment:
      MYSQL_DATABASE: 'akuntansi_dev'
      MYSQL_USER: 'dimas'
      MYSQL_PASSWORD: 'dimas1950'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3308:3306'
    volumes:
      - akuntansi_dev_db:/var/lib/mysql
    networks:
      - akuntansi_dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  akuntansi_dev_db:
